package com.school.sis.grade.service;
import com.school.sis.common.exception.*; import com.school.sis.grade.dto.*; import com.school.sis.grade.entity.*; import com.school.sis.grade.repository.*; import com.school.sis.setup.entity.ActiveStatus; import com.school.sis.setup.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service public class GradingSetupService {
 private final GradingScaleRepository scales; private final GradingTemplateRepository templates; private final ClassGradebookRepository gradebooks; private final ProgramRepository programs; private final CourseRepository courses;
 public GradingSetupService(GradingScaleRepository s,GradingTemplateRepository t,ClassGradebookRepository g,ProgramRepository p,CourseRepository c){scales=s;templates=t;gradebooks=g;programs=p;courses=c;}
 @Transactional(readOnly=true) public List<GradingScaleResponse> scales(){return scales.findAll().stream().map(this::scaleResponse).toList();}
 @Transactional(readOnly=true) public GradingScaleResponse scale(UUID id){return scaleResponse(findScale(id));}
 @Transactional public GradingScaleResponse saveScale(UUID id,GradingScaleRequest r){if(id!=null&&gradebooks.existsByScaleId(id))throw new BusinessRuleException("Used grading scales are immutable; create a new version");validateBands(r.bands());GradingScale s=id==null?new GradingScale():findScale(id);s.setScaleCode(r.scaleCode().trim());s.setScaleName(r.scaleName().trim());s.setVersion(r.version());s.setStatus(r.status()==null?ActiveStatus.ACTIVE:r.status());s.setBands(r.bands().stream().map(b->{GradingScaleBand x=new GradingScaleBand();x.setMinimumPercentage(b.minimumPercentage());x.setMaximumPercentage(b.maximumPercentage());x.setGradePoint(b.gradePoint());x.setRemark(b.remark());return x;}).toList());return scaleResponse(scales.save(s));}
 @Transactional(readOnly=true) public List<GradingTemplateResponse> templates(UUID programId,UUID courseId){return templates.findAll().stream().filter(t->programId==null||t.getProgram().getId().equals(programId)).filter(t->courseId==null||t.getCourse().getId().equals(courseId)).map(this::templateResponse).toList();}
 @Transactional(readOnly=true) public GradingTemplateResponse template(UUID id){return templateResponse(findTemplate(id));}
 @Transactional public GradingTemplateResponse saveTemplate(UUID id,GradingTemplateRequest r){if(id!=null&&gradebooks.existsByTemplateId(id))throw new BusinessRuleException("Used grading templates are immutable; create a new version");validateWeights(r);GradingTemplate t=id==null?new GradingTemplate():findTemplate(id);t.setTemplateCode(r.templateCode().trim());t.setTemplateName(r.templateName().trim());t.setProgram(programs.findById(r.programId()).orElseThrow(()->new NotFoundException("Program not found")));t.setCourse(courses.findById(r.courseId()).orElseThrow(()->new NotFoundException("Course not found")));t.setScale(findScale(r.scaleId()));t.setVersion(r.version());t.setMidtermWeight(r.midtermWeight());t.setFinalWeight(r.finalWeight());t.setStatus(r.status()==null?ActiveStatus.ACTIVE:r.status());t.setCategories(r.categories().stream().map(c->{GradingTemplateCategory x=new GradingTemplateCategory();x.setPeriod(c.period());x.setCategoryName(c.categoryName().trim());x.setWeight(c.weight());x.setSortOrder(c.sortOrder());return x;}).toList());return templateResponse(templates.save(t));}
 private void validateWeights(GradingTemplateRequest r){if(r.midtermWeight().add(r.finalWeight()).compareTo(new BigDecimal("100"))!=0)throw new BusinessRuleException("Midterm and final weights must total 100");for(GradingPeriod p:GradingPeriod.values()){BigDecimal total=r.categories().stream().filter(c->c.period()==p).map(GradingTemplateRequest.Category::weight).reduce(BigDecimal.ZERO,BigDecimal::add);if(total.compareTo(new BigDecimal("100"))!=0)throw new BusinessRuleException(p+" category weights must total 100");}}
 private void validateBands(List<GradingScaleRequest.Band> bands){List<GradingScaleRequest.Band> sorted=bands.stream().sorted(Comparator.comparing(GradingScaleRequest.Band::minimumPercentage)).toList();BigDecimal expected=BigDecimal.ZERO;for(var b:sorted){if(b.minimumPercentage().compareTo(expected)!=0||b.maximumPercentage().compareTo(b.minimumPercentage())<0)throw new BusinessRuleException("Scale bands must cover 0 through 100 without gaps or overlaps");expected=b.maximumPercentage().add(new BigDecimal("0.01"));}if(sorted.isEmpty()||sorted.getLast().maximumPercentage().compareTo(new BigDecimal("100"))!=0)throw new BusinessRuleException("Scale bands must cover 0 through 100 without gaps or overlaps");}
 private GradingScale findScale(UUID id){return scales.findById(id).orElseThrow(()->new NotFoundException("Grading scale not found"));} private GradingTemplate findTemplate(UUID id){return templates.findById(id).orElseThrow(()->new NotFoundException("Grading template not found"));}
 private GradingScaleResponse scaleResponse(GradingScale s){return new GradingScaleResponse(s.getId(),s.getScaleCode(),s.getScaleName(),s.getVersion(),s.getStatus(),s.getBands().stream().sorted(Comparator.comparing(GradingScaleBand::getMinimumPercentage)).map(b->new GradingScaleResponse.Band(b.getId(),b.getMinimumPercentage(),b.getMaximumPercentage(),b.getGradePoint(),b.getRemark())).toList());}
 private GradingTemplateResponse templateResponse(GradingTemplate t){return new GradingTemplateResponse(t.getId(),t.getTemplateCode(),t.getTemplateName(),t.getProgram().getId(),t.getProgram().getProgramCode(),t.getCourse().getId(),t.getCourse().getCourseCode(),t.getScale().getId(),t.getScale().getScaleName(),t.getVersion(),t.getMidtermWeight(),t.getFinalWeight(),t.getStatus(),t.getCategories().stream().sorted(Comparator.comparing(GradingTemplateCategory::getPeriod).thenComparing(GradingTemplateCategory::getSortOrder)).map(c->new GradingTemplateResponse.Category(c.getId(),c.getPeriod(),c.getCategoryName(),c.getWeight(),c.getSortOrder())).toList());}
}
