package com.school.sis.student.portal;

import com.school.sis.auth.security.SisUserDetails;
import com.school.sis.audit.service.AuditService;
import com.school.sis.common.exception.BusinessRuleException;
import com.school.sis.common.response.ApiResponse;
import com.school.sis.storage.FileStorageService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.time.Instant;
import java.util.*;

@RestController @RequestMapping("/api/v1/student-portal-admin") @PreAuthorize("hasAuthority('STUDENT_PORTAL_ADMIN')")
public class StudentPortalAdminController {
    private static final Set<String> REQUEST_STATES=Set.of("PROCESSING","READY","COMPLETED","REJECTED");
    private final JdbcTemplate jdbc;private final FileStorageService storage;private final AuditService audit;
    public StudentPortalAdminController(JdbcTemplate jdbc,FileStorageService storage,AuditService audit){this.jdbc=jdbc;this.storage=storage;this.audit=audit;}
    @GetMapping("/settings") public ApiResponse<List<Map<String,Object>>> settings(){return ApiResponse.success("Student portal settings retrieved",jdbc.queryForList("select ps.*,sy.school_year as \"schoolYear\",sm.name as \"semesterName\" from student_portal_term_settings ps join school_years sy on sy.id=ps.school_year_id join semesters sm on sm.id=ps.semester_id order by sy.school_year desc,sm.sort_order"));}
    @PutMapping("/settings/{id}") public ApiResponse<Map<String,Object>> settings(@PathVariable UUID id,@Valid @RequestBody Settings r,@AuthenticationPrincipal SisUserDetails p){int changed=jdbc.update("update student_portal_term_settings set enrollment_enabled=?,enrollment_opens_at=?,enrollment_closes_at=?,attendance_visible=?,portal_notice=?,updated_by=?,updated_at=now() where id=?",r.enrollmentEnabled(),r.enrollmentOpensAt(),r.enrollmentClosesAt(),r.attendanceVisible(),r.portalNotice(),p.id(),id);if(changed==0)throw new BusinessRuleException("Portal setting not found");audit.log("STUDENT_PORTAL_SETTINGS_UPDATED","STUDENT","StudentPortalTermSetting",id,null,Map.of("enrollmentEnabled",r.enrollmentEnabled(),"attendanceVisible",r.attendanceVisible()));return ApiResponse.success("Student portal settings updated",jdbc.queryForMap("select * from student_portal_term_settings where id=?",id));}
    @GetMapping("/announcements") public ApiResponse<List<Map<String,Object>>> announcements(){return ApiResponse.success("Academic notices retrieved",jdbc.queryForList("select id,title,body,audience,program_id as \"programId\",year_level as \"yearLevel\",status,published_at as \"publishedAt\",created_at as \"createdAt\" from portal_announcements order by created_at desc"));}
    @PostMapping("/announcements") public ApiResponse<Map<String,Object>> announcement(@Valid @RequestBody Announcement r,@AuthenticationPrincipal SisUserDetails p){if(!Set.of("ALL","PROGRAM","YEAR_LEVEL").contains(r.audience())||!Set.of("DRAFT","PUBLISHED","ARCHIVED").contains(r.status()))throw new BusinessRuleException("Invalid announcement state");UUID id=UUID.randomUUID();jdbc.update("insert into portal_announcements(id,title,body,audience,program_id,year_level,status,published_at,author_id) values(?,?,?,?,?,?,?,case when ?='PUBLISHED' then now() end,?)",id,r.title().trim(),r.body().trim(),r.audience(),r.programId(),r.yearLevel(),r.status(),r.status(),p.id());return ApiResponse.success("Academic notice saved",jdbc.queryForMap("select id,title,status from portal_announcements where id=?",id));}
    @GetMapping("/forms") public ApiResponse<List<Map<String,Object>>> forms(){return ApiResponse.success("Forms retrieved",jdbc.queryForList("select id,title,description,original_filename as filename,status,created_at as \"createdAt\" from student_forms order by created_at desc"));}
    @PostMapping(value="/forms",consumes="multipart/form-data") public ApiResponse<Map<String,Object>> form(@RequestParam String title,@RequestParam(required=false) String description,@RequestParam(defaultValue="PUBLISHED") String status,@RequestPart MultipartFile file,@AuthenticationPrincipal SisUserDetails p){if(!Set.of("DRAFT","PUBLISHED","ARCHIVED").contains(status))throw new BusinessRuleException("Invalid form status");var stored=storage.storeForm(file);UUID id=UUID.randomUUID();jdbc.update("insert into student_forms(id,title,description,original_filename,stored_filename,mime_type,file_size,status,published_at,uploaded_by) values(?,?,?,?,?,?,?,?,case when ?='PUBLISHED' then now() end,?)",id,title.trim(),description,stored.originalFilename(),stored.storedFilename(),stored.mimeType(),stored.size(),status,status,p.id());return ApiResponse.success("Student form uploaded",jdbc.queryForMap("select id,title,status from student_forms where id=?",id));}
    @GetMapping("/requests") public ApiResponse<List<Map<String,Object>>> requests(){return ApiResponse.success("Student requests retrieved",jdbc.queryForList("select sr.id,s.student_number as \"studentNumber\",concat(s.last_name,', ',s.first_name) as \"studentName\",sr.request_type as \"requestType\",sr.document_name as \"documentName\",sr.purpose,sr.status,sr.staff_comment as \"staffComment\",sr.created_at as \"createdAt\" from student_service_requests sr join students s on s.id=sr.student_id order by sr.created_at desc"));}
    @PatchMapping("/requests/{id}") public ApiResponse<Map<String,Object>> request(@PathVariable UUID id,@Valid @RequestBody RequestState r,@AuthenticationPrincipal SisUserDetails p){if(!REQUEST_STATES.contains(r.status()))throw new BusinessRuleException("Invalid request state");var current=jdbc.queryForList("select status from student_service_requests where id=? for update",id);if(current.isEmpty())throw new BusinessRuleException("Request not found");String from=(String)current.getFirst().get("status");if(Set.of("COMPLETED","REJECTED","CANCELLED").contains(from))throw new BusinessRuleException("Completed requests cannot be changed");jdbc.update("update student_service_requests set status=?,staff_comment=?,handled_by=?,handled_at=now(),updated_at=now() where id=?",r.status(),r.comment(),p.id(),id);jdbc.update("insert into student_service_request_history(request_id,from_status,to_status,comment,changed_by) values(?,?,?,?,?)",id,from,r.status(),r.comment(),p.id());audit.log("STUDENT_REQUEST_STATUS_CHANGED","STUDENT","StudentServiceRequest",id,Map.of("status",from),Map.of("status",r.status()));return ApiResponse.success("Student request updated",jdbc.queryForMap("select id,status,staff_comment as \"staffComment\" from student_service_requests where id=?",id));}
    @PostMapping(value="/requests/{id}/fulfillment",consumes="multipart/form-data") public ApiResponse<Map<String,Object>> fulfill(@PathVariable UUID id,@RequestPart MultipartFile file,@RequestParam(required=false) String comment,@AuthenticationPrincipal SisUserDetails p){var current=jdbc.queryForList("select status from student_service_requests where id=? for update",id);if(current.isEmpty())throw new BusinessRuleException("Request not found");String from=(String)current.getFirst().get("status");if(!Set.of("SUBMITTED","PROCESSING").contains(from))throw new BusinessRuleException("Only open requests can be fulfilled");var stored=storage.storeRequest(file);jdbc.update("update student_service_requests set status='READY',staff_comment=?,fulfilled_filename=?,fulfilled_stored_filename=?,fulfilled_mime_type=?,handled_by=?,handled_at=now(),updated_at=now() where id=?",comment,stored.originalFilename(),stored.storedFilename(),stored.mimeType(),p.id(),id);jdbc.update("insert into student_service_request_history(request_id,from_status,to_status,comment,changed_by) values(?,?,'READY',?,?)",id,from,comment,p.id());audit.log("STUDENT_REQUEST_FULFILLED","STUDENT","StudentServiceRequest",id,Map.of("status",from),Map.of("status","READY"));return ApiResponse.success("Fulfilled document uploaded",jdbc.queryForMap("select id,status,fulfilled_filename as \"fulfilledFilename\" from student_service_requests where id=?",id));}
    @PostMapping("/enrollments/{id}/return") public ApiResponse<Void> returnEnrollment(@PathVariable UUID id,@RequestBody ReturnReason r,@AuthenticationPrincipal SisUserDetails p){int changed=jdbc.update("update enrollments set status='DRAFT',remarks=?,submitted_at=null,updated_at=now() where id=? and status='SUBMITTED'",r.reason(),id);if(changed==0)throw new BusinessRuleException("Only submitted enrollments can be returned");jdbc.update("insert into enrollment_status_history(id,enrollment_id,from_status,to_status,remarks) values(gen_random_uuid(),?,'SUBMITTED','DRAFT',?)",id,r.reason());audit.log("STUDENT_ENROLLMENT_RETURNED","ENROLLMENT","Enrollment",id,Map.of("status","SUBMITTED"),Map.of("status","DRAFT"));return ApiResponse.success("Enrollment returned to student");}
    public record Settings(boolean enrollmentEnabled,Instant enrollmentOpensAt,Instant enrollmentClosesAt,boolean attendanceVisible,String portalNotice){}
    public record Announcement(@NotBlank String title,@NotBlank String body,@NotBlank String audience,UUID programId,Integer yearLevel,@NotBlank String status){}
    public record RequestState(@NotBlank String status,String comment){}
    public record ReturnReason(@NotBlank String reason){}
}
