import { Link } from "react-router-dom"
import { Bell, BookOpen, CalendarDays, ChevronRight, MapPin } from "lucide-react"
import { useAuth } from "@/lib/auth"
import { useFacultyDashboard } from "@/hooks/use-faculty-portal"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

const time=(v:string)=>v?.slice(0,5)
export default function FacultyDashboardPage(){const {user}=useAuth(),q=useFacultyDashboard();if(q.isLoading)return <div className="p-8"><Skeleton className="h-[560px] w-full"/></div>;const d=q.data;const first=user?.fullName.split(" ")[0]??"Faculty";return <div className="mx-auto max-w-[1320px] p-4 sm:p-6 lg:p-8">
  <h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-[1.75rem]">Good morning, {first}</h1><p className="mt-2 text-base text-muted-foreground">Here’s what needs your attention today.</p>
  <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="overflow-hidden rounded-lg border border-border"><div className="flex h-16 items-center justify-between border-b px-5"><h2 className="flex items-center gap-3 font-semibold"><CalendarDays/>Today’s Schedule</h2><Button asChild variant="ghost"><Link to="/faculty/schedule">View full schedule<ChevronRight data-icon="inline-end"/></Link></Button></div><div className="flex flex-col gap-3 p-3">{d?.today.length?d.today.map((x,i)=><Link to={`/faculty/classes/${x.scheduleId}`} key={`${x.scheduleId}-${x.startTime}`} className="grid grid-cols-[108px_1fr] overflow-hidden rounded-md border hover:bg-surface"><div className={`flex items-center border-r-4 px-4 font-semibold ${i%2?"border-r-success-foreground bg-success text-success-foreground":"border-r-info-foreground bg-info text-info-foreground"}`}>{time(x.startTime)}–<br/>{time(x.endTime)}</div><div className="p-4"><p className="font-semibold">{x.courseCode} · {x.sectionCode}</p><p className="text-sm text-muted-foreground">{x.courseTitle}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin/>{x.roomCode}</p></div></Link>):<p className="p-8 text-center text-sm text-muted-foreground">No classes scheduled today.</p>}</div></section>
  <section className="overflow-hidden rounded-lg border border-border"><div className="flex h-16 items-center justify-between border-b px-5"><h2 className="flex items-center gap-3 font-semibold"><Bell/>Action needed</h2></div><div>{(d?.classes??[]).filter(x=>x.gradeStatus==="RETURNED_FOR_CORRECTION").map(x=><div key={x.scheduleId} className="flex items-center justify-between border-b p-5"><div><p className="font-semibold text-destructive">Returned for correction</p><p className="text-sm text-muted-foreground">{x.courseCode} · {x.courseTitle}</p></div><Button asChild variant="outline"><Link to={`/faculty/classes/${x.scheduleId}?tab=gradebook`}>Open gradebook</Link></Button></div>)}{!d?.returnedGradebooks?<div className="p-8 text-center text-sm text-muted-foreground">You’re all caught up.</div>:null}</div></section></div>
  <section className="mt-6 overflow-hidden rounded-lg border border-border"><div className="flex h-16 items-center justify-between border-b px-5"><h2 className="flex items-center gap-3 font-semibold"><BookOpen/>My classes</h2><Button asChild variant="ghost"><Link to="/faculty/classes">View all classes<ChevronRight data-icon="inline-end"/></Link></Button></div><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Class</TableHead><TableHead>Room</TableHead><TableHead>Students</TableHead><TableHead>Attendance</TableHead><TableHead>Grades</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{d?.classes.map(x=><TableRow key={x.scheduleId}><TableCell><p className="font-semibold">{x.courseCode} · {x.sectionCode}</p><p className="text-xs text-muted-foreground">{x.courseTitle}</p></TableCell><TableCell>{x.roomCode}</TableCell><TableCell>{x.studentCount}</TableCell><TableCell>{x.attendanceCount?`${x.attendanceCount} recorded`:"Not recorded"}</TableCell><TableCell>{x.gradeStatus.replaceAll("_"," ")}</TableCell><TableCell className="text-right"><Button asChild variant="outline" size="sm"><Link to={`/faculty/classes/${x.scheduleId}`}>Open class</Link></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y md:hidden">{d?.classes.map(x=><article key={x.scheduleId} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{x.courseCode} · {x.sectionCode}</p><p className="text-sm text-muted-foreground">{x.courseTitle}</p></div><Button asChild size="sm" variant="outline"><Link to={`/faculty/classes/${x.scheduleId}`}>Open</Link></Button></div><dl className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><dt className="text-muted-foreground">Room</dt><dd>{x.roomCode}</dd></div><div><dt className="text-muted-foreground">Students</dt><dd>{x.studentCount}</dd></div><div><dt className="text-muted-foreground">Grades</dt><dd>{x.gradeStatus.replaceAll("_"," ")}</dd></div></dl></article>)}</div></section>
</div>}
