package com.school.sis.grade.controller;
import com.school.sis.auth.security.SisUserDetails; import com.school.sis.common.response.*; import com.school.sis.grade.dto.*; import com.school.sis.grade.entity.GradeStatus; import com.school.sis.grade.service.GradebookService; import jakarta.validation.Valid; import org.springframework.data.domain.Pageable; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.UUID;
@RestController @RequestMapping("/api/v1/gradebooks") @PreAuthorize("hasAnyAuthority('GRADE_ENCODE','GRADE_REVIEW','GRADE_LOCK','GRADE_APPROVE')") public class GradebookController {
 private final GradebookService service; public GradebookController(GradebookService s){service=s;}
 @GetMapping("/classes") public ApiResponse<PageResponse<GradeClassSummaryResponse>> classes(@RequestParam(defaultValue="MY") String scope,@RequestParam(required=false) UUID schoolYearId,@RequestParam(required=false) UUID semesterId,@RequestParam(required=false) GradeStatus status,@RequestParam(required=false) String search,Pageable page,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Grade classes retrieved",service.classes(scope,schoolYearId,semesterId,status,search,page,user));}
 @GetMapping("/class/{scheduleId}") public ApiResponse<GradebookResponse> get(@PathVariable UUID scheduleId,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Gradebook retrieved",service.get(scheduleId,user));}
 @PostMapping("/class/{scheduleId}/initialize") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> initialize(@PathVariable UUID scheduleId,@Valid @RequestBody GradebookRequests.Initialize r,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Gradebook initialized",service.initialize(scheduleId,r.templateId(),user));}
 @PostMapping("/class/{scheduleId}/items") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> item(@PathVariable UUID scheduleId,@Valid @RequestBody GradebookRequests.Item r,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Assessment item saved",service.saveItem(scheduleId,r,user));}
 @PutMapping("/class/{scheduleId}/items/{id}") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> updateItem(@PathVariable UUID scheduleId,@PathVariable UUID id,@Valid @RequestBody GradebookRequests.Item r,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Assessment item saved",service.saveItem(scheduleId,new GradebookRequests.Item(id,r.categoryId(),r.title(),r.maximumScore(),r.dueDate(),r.sortOrder()),user));}
 @DeleteMapping("/class/{scheduleId}/items/{id}") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> archiveItem(@PathVariable UUID scheduleId,@PathVariable UUID id,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Assessment item archived",service.archiveItem(scheduleId,id,user));}
 @PutMapping("/class/{scheduleId}/scores") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> scores(@PathVariable UUID scheduleId,@Valid @RequestBody GradebookRequests.Scores r,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Scores saved",service.saveScores(scheduleId,r,user));}
 @PutMapping("/class/{scheduleId}/overrides") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> override(@PathVariable UUID scheduleId,@Valid @RequestBody GradebookRequests.Override r,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Result override saved",service.saveOverride(scheduleId,r,user));}
 @DeleteMapping("/class/{scheduleId}/overrides/{subjectId}") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> removeOverride(@PathVariable UUID scheduleId,@PathVariable UUID subjectId,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Result override removed",service.removeOverride(scheduleId,subjectId,user));}
 @PostMapping("/class/{scheduleId}/submit") @PreAuthorize("hasAuthority('GRADE_ENCODE')") public ApiResponse<GradebookResponse> submit(@PathVariable UUID scheduleId,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Gradebook submitted",service.submit(scheduleId,user));}
 @PostMapping("/class/{scheduleId}/return") @PreAuthorize("hasAuthority('GRADE_REVIEW')") public ApiResponse<GradebookResponse> returned(@PathVariable UUID scheduleId,@Valid @RequestBody GradebookRequests.Return r,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Gradebook returned",service.returnForCorrection(scheduleId,r.reason(),user));}
 @PostMapping("/class/{scheduleId}/approve") @PreAuthorize("hasAuthority('GRADE_REVIEW')") public ApiResponse<GradebookResponse> approve(@PathVariable UUID scheduleId,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Gradebook approved",service.approve(scheduleId,user));}
 @PostMapping("/class/{scheduleId}/lock") @PreAuthorize("hasAuthority('GRADE_LOCK')") public ApiResponse<GradebookResponse> lock(@PathVariable UUID scheduleId,@AuthenticationPrincipal SisUserDetails user){return ApiResponse.success("Gradebook locked",service.lock(scheduleId,user));}
}
